# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5041e943e74ac42532ba8c81fa7cba1da6d8d08aa708a9e81012000b8253fb5d7f07e1374333f04ece1d1022003517b1b5bec21eeaf554028a9820b9fdaff078

test:
  secret_key_base: 2022052d60b2fff5c1785223ec5c6467b807eed35585296ef6323c9c4e0212dc1076bcf6e064cbebf16d93d9576af3fa82751f090c0b39c722cf77928d0393e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
